### PR TITLE
refactor and add test case

### PR DESCRIPTION
**Pull request by ExitedState**
# Description

add testcase and refactor isNumber function

## Type of change

Please delete options that are not relevant.

- [ ] Refactor or other

# Checklist:

- [ ] I have run `pnpm format` and my code don't have any linting issues
  
  
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by ExitedState** [comment]
I refactor something and sorry for my confuse in previous PR krubb @01110111-wave

**Comment by ExitedState** [comment]
you need to implement [TODO ](https://github.com/01110111-wave/kaogeek-discord-bot/pull/2/files#diff-7a0a87e5b8491686d9b6bdc58df5732df97643b39f45d8bcf814ba0a228aa37bL75) and merge this PR.

 Anyway, you can just copy it to your work; it'll be fine.

**Comment by ExitedState** [comment]
you need to implement [TODO ](https://github.com/01110111-wave/kaogeek-discord-bot/pull/2/files#diff-7a0a87e5b8491686d9b6bdc58df5732df97643b39f45d8bcf814ba0a228aa37bL75) and merge this PR. (for workflow approval)

**but I think the best way is just copy my code to your work.**

**Comment by 01110111-wave** [comment]
I have read your first commit then edit logic based your PR and retest my code with your test. However, I do not commit the new test into the PR, because I will make separated PR about it later. (Putting everything into a pull request might resulted in trouble.)
About TODO, soon I will implement mute command which create the moderation log that note if it is severe mute punishment or not, and the TODO will use this log to check whether it is severe punishment.
Also, I truly appreciate your new test. It really points where my flaw is.

**Comment by ExitedState** [comment]
ok krubbb

**Pull request closed without merging**
